[package]
name = "settings"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { path = "../../libs/config" }
ipsea = { path = "../../libs/ipc", package = "ipc" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.43", features = ["full"] }
ui = { version = "0.1.0", path = "../../libs/ui" }
system = { path = "../../libs/system" }
rfd = "0.17"

freya = { git = "https://github.com/marc2332/freya", branch = "main", features = ["all"] }
freya-performance-plugin = { git = "https://github.com/marc2332/freya", branch = "main"}
freya-devtools = { git = "https://github.com/marc2332/freya", branch = "main", features = ["server"] }

[[bin]]
name = "settings"
path = "src/main.rs"
