[package]
name = "session-lock"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "finick-lock"
path = "src/main.rs"

[dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
calloop = { version = "0.14", features = ["signals"] }
calloop-wayland-source = "0.4"
tempfile = "3"
system = { path = "../../libs/system" }
config = { path = "../../libs/config" }
xkbcommon-dl = "0.4"
zbus = { version = "5", default-features = false, features = ["blocking-api", "async-io"] }
image = "0.24"
ab_glyph = "0.2"
chrono = "0.4"
